### ISSUE TITLE
Refresh and Remove buttons not working on Firefox

### ISSUE THREAD

**Issue by MikaelSvenn** [joelpitk/metar.fi#1]
Using Firefox Quantum 58.0.1 (64-bit) with all plugins disabled, the "Refresh" and "Remove" buttons do not work. Clicking them does nothing:
 - Refresh doesn't refresh the card
 - Remove doesn't close the card

No errors appear in the console either.

**Comment by joelpitk** [comment]
Fixed in ee94a9040f778a4ca210f8e9fb0115c4258af2b0 and d68ed8c3fc8e4878cf2a68a5eba90913990ff39c.
